CREATE DATABASE IF NOT EXISTS HETAV;

USE HETAV;

CREATE TABLE IF NOT EXISTS c4(
    id INT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    enrollment_no INT UNIQUE
);

DESC c4;

INSERT INTO c4
VALUES
(1, "Hetav Shah", 220179),
(2, "a", 220128),
(3, "b", 220189),
(4, "c", 220274),
(5, "d", 220253),
(6, "HEHEHEEHEHHEHE", 220292);

SELECT * FROM c4;

CREATE USER IF NOT EXISTS BigPapa IDENTIFIED BY 'Pass@2106';

GRANT SELECT, INSERT, UPDATE, DELETE ON c4 TO BigPapa;

REVOKE DELETE ON c4 FROM BigPapa;

DROP USER IF EXISTS BigPapa;

DROP DATABASE IF EXISTS HETAV;